version: '2'
services:
    workshop-app:
        image: workshop
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://workshop-postgresql:5432/workshop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=workshop-elasticsearch:9300
        ports:
            - 8080:8080
    workshop-postgresql:
        extends:
            file: postgresql.yml
            service: workshop-postgresql
    workshop-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: workshop-elasticsearch
